name: 'Merge to QA'
on:
  workflow_dispatch:
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          github_token: ${{ github.token }}
          source_ref: ${{ github.ref }}
          target_branch: 'qa'
          commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'
